name: ci-rsc

permissions: {}

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "packages/plugin-rsc/**"
      - "pnpm-lock.yaml"
      - ".github/workflows/ci-rsc.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - run: pnpm i
      - run: pnpm build
      - run: pnpm -C packages/plugin-rsc tsc
      - run: pnpm -C packages/plugin-rsc test

  test-e2e:
    name: test-rsc (${{ matrix.os }} / ${{ matrix.browser }}) ${{ matrix.rolldown == true && '(rolldown)' || '' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        browser: [chromium]
        rolldown: [false]
        include:
          - os: ubuntu-latest
            browser: firefox
          - os: macos-latest
            browser: webkit
          - os: ubuntu-latest
            browser: chromium
            rolldown: true
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - run: pnpm i
      - run: pnpm build
      - name: install rolldown
        if: ${{ matrix.rolldown }}
        run: |
          echo 'overrides: { vite: "npm:rolldown-vite@latest" }' >> pnpm-workspace.yaml
          pnpm i --no-frozen-lockfile
      - run: pnpm -C packages/plugin-rsc exec playwright install ${{ matrix.browser }}
      - run: pnpm -C packages/plugin-rsc test-e2e-ci --project=${{ matrix.browser }}
        env:
          TEST_ISOLATED: ${{ matrix.os === 'windows-latest' && 'false' || 'true' }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.os }}-${{ matrix.browser }}
          path: |
            packages/plugin-rsc/test-results
